### ISSUE TITLE
Fix QuickStatement runs 6590 & 6591

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/ideas#1099]
- [6590](https://tools.wmflabs.org/quickstatements/#/batch/6590)
- [6591](https://tools.wmflabs.org/quickstatements/#/batch/6591)

as per https://www.wikidata.org/w/index.php?title=Wikidata:Edit_groups/QSv2/6590&oldid=prev&diff=823924766&diffmode=source

**Comment by Daniel-Mietchen** [comment]
Best solution is probably to 
- check for items that have 
  - an ORCID AND
  - an occupation "researcher" AND
  - at least one other occupation, where the "researcher" occupation has no reference

**Comment by Daniel-Mietchen** [comment]
As per #1100 , 

> there are no <code> P106 = wd:Q1650915 </code> statements with references involving [P248](https://www.wikidata.org/wiki/Property:P248) or [P854](https://www.wikidata.org/wiki/Property:P854).

This means that we can safely remove <code>P106 = wd:Q1650915</code> statements when there is another P106 statement.

**Comment by Daniel-Mietchen** [comment]
As per #1101, there are currently 6013 items with an ORCID where the <code>P106 = wd:Q1650915</code> statement is complemented by another </code>P106</code> statement. 

I will now set up a QuickStatements run to remove these.

**Comment by Daniel-Mietchen** [comment]
The batch is now up at https://tools.wmflabs.org/quickstatements/#/batch/6669 .

**Comment by Daniel-Mietchen** [comment]
For reference, batches
- [6610](https://tools.wmflabs.org/quickstatements/#/batch/6610)
and
- [6611](https://tools.wmflabs.org/quickstatements/#/batch/6611)
worked as 6590 and 6591 were intended.

There are still over 100k items with ORCID and no P106 statement, as per [this query](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fauthor%20%23%3FauthorLabel%20%28COUNT%28%3Fpaper%29%20AS%20%3Fcount%29%0AWHERE%0A%7B%0A%20%20%20%20%3Fauthor%20wdt%3AP496%20%3Forcid%20.%0A%23%20%20%20%20%3Fpaper%20wdt%3AP50%20%3Fauthor%20.%0A%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%20%3Fauthor%20wdt%3AP106%20%3Foccupation%20.%20%7D%0A%23%09SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22%20%7D%0A%7D%0A%23GROUP%20BY%20%3Fauthor%20%3FauthorLabel%0A%23ORDER%20BY%20DESC%28%3Fcount%29%0ALIMIT%20100000). I'll keep working on them in batches of 20k.

**Comment by Daniel-Mietchen** [comment]
The batch has finished, and the one remaining error is due to [an identical edit](https://www.wikidata.org/w/index.php?title=Q54958112&type=revision&diff=825118748&oldid=823620200&diffmode=source) by another user.

**Comment by sabas** [comment]
Hi,
I don't understand the reasoning in this edit, do you mean that if a researcher has another part time occupation, he couldn't be defined by its main activity?

**Comment by Daniel-Mietchen** [comment]
@sabas I think the reasoning is that we should try to be a bit more precise than "researcher", e.g. say "theoretical physicist" or "epidemiologist" or some such.
