### ISSUE TITLE
Submit an abstract to the 2023 Digital Data in Biodiversity Research Conference (5-7 June)

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/ideas#1751]
as per
https://www.idigbio.org/content/digital-data-2023-leveraging-digital-data-service-conservation-ecology-systematics .
Submission deadline: April 26.

Probably of interest to @jhpoelen too.

**Comment by Daniel-Mietchen** [comment]
In the end, I did not submit anything here, as that event is parallel to one that I help organize, https://hiknowledgeworkshops.com/2023/02/20/next-in-person-workshop-june-5-7-2023/ .

**Comment by jhpoelen** [comment]
@Daniel-Mietchen thanks for sharing and for closing the loop on this.

Also, the event you are organizing looks like fun - 

> Next workshop – June 5-6, 2023
> As a follow up to [last year’s online workshop](https://hiknowledgeworkshops.wordpress.com/workshop-1/), we are currently organizing a new workshop, this time in person in Berlin, Germany. It will take place over two days, from the 5th to the 6th of June 2023, and will include keynote speakers and focus workshop sessions. We will discuss the concepts and questions structuring invasion ecology, test out new synthesis and community building tools, as well as design meaningful semantic data structures to enhance scientific publication and help research synthesis.

Wish I could join!

**Comment by Daniel-Mietchen** [comment]
@jhpoelen The Monday morning part is hybrid, but I guess you'd prefer to get some sleep then. Let me know if not. All the rest is in person this time.
