### ISSUE TITLE
OpenCon doathon sessions I might be able to help with

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/ideas#582]
The weekend is over, and I am attending [another conference](https://www.wglf.bicentennial.virginia.edu/) now, so cannot do much *during* the [OpenCon doathon](https://github.com/sparcopen/doathon/issues), but I see those tickets as conversation starters and plan to regularly review them.

For now, I'm just collecting links to tickets to which I think I can contribute (to some, I [already did](https://github.com/sparcopen/doathon/issues/62), for others, I [plan to](https://github.com/sparcopen/doathon/issues/65)). Feel free to ping me if you think my input would be useful.

**Comment by KoenVermeir** [comment]
good! love to see your input!

**Comment by KoenVermeir** [comment]
we will continue to post over the next days

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/44 - on learning moments

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/17 - on African open science

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/68 - peer review of open data

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/45 - overview of non-textbook OER

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/46 - on OAbot, which is unfortunately still not about  licensing or Wikidata integration

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/48 - on a Dataverse-based repository

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/49 - on a bot for integration of ORCID/ Crossref data into Wikidata

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/57 - on making data sharing routine

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/61 - on sharing open stories

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/65 - on open conference questions

**Comment by Daniel-Mietchen** [comment]
https://github.com/sparcopen/doathon/issues/66 - OA in Asia

**Comment by Daniel-Mietchen** [comment]
Probably worth mentioning that this all relates to https://github.com/Daniel-Mietchen/events/issues/92 .
